FYPFinal/Controllers/DashController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChartLibrary;

namespace FYPFinal.Controllers
{
    public class DashController : Controller
    {
        // GET: Dash
        public ActionResult Dash()
        {
            return View();
        }
    }
}

FYPFinal/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPFinal.Models;

namespace FYPFinal.Controllers
{
    public class ListController : Controller
    {
        // GET: List
        //public ActionResult Index()
        //{
        //    return View();
        //}

        // List action
        public ActionResult Index()
        {
            FYPEntities db = new FYPEntities();
            List<VoteFinal> votefinal = new List<VoteFinal>();
            votefinal = db.VoteFinals.ToList();
            return View(votefinal);
        }

        // deleting rows action
        public ActionResult Delete(string[] ids)
        {
            // delete selected rows
            int[] id = null;
            if (ids != null)
            {
                id = new int[ids.Length];
                int j = 0;
                foreach (string i in ids)
                {
                    int.TryParse(i, out id[j++]);
                }
            }

            if (id != null && id.Length > 0)
            {
                List<VoteFinal> allSelected = new List<VoteFinal>();
                FYPEntities db = new FYPEntities();
                allSelected = db.VoteFinals.Where(x => id.Contains(x.Vid)).ToList();
                foreach (var i in allSelected)
                {
                    db.VoteFinals.Remove(i);
                }
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

FYPFinal/Views/Admin/Create.cshtml
@model FYPFinal.Models.VoteFinal

@{
    ViewBag.Title = "Create";
}



<head>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <meta charset="utf-8">
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Blog style customer stylesheet https://startbootstrap.com/template-overviews/blog-home/-->
    <link href="~/css/blog-home.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin.min.css" rel="stylesheet">
    <link href="~/vendor/datatables/dataTables.bootstrap4.js" rel="stylesheet">
    <link href="~/css/half-slider.css" rel="stylesheet">
    <link href="css/grayscale.min.css" rel="stylesheet">
</head>
<h1>Create New Voting Records</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>VTestTbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VBitcoin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VBitcoin)
                    @Html.ValidationMessageFor(model => model.VBitcoin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VEthereum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VEthereum)
                    @Html.ValidationMessageFor(model => model.VEthereum, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VBitcoinCash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VBitcoinCash)
                    @Html.ValidationMessageFor(model => model.VBitcoinCash, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VLitecoin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VLitecoin)
                    @Html.ValidationMessageFor(model => model.VLitecoin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VRipple, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VRipple)
                    @Html.ValidationMessageFor(model => model.VRipple, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Home", "Dash", "Dash")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FYPFinal/Views/Admin/Edit.cshtml
@model FYPFinal.Models.VoteFinal

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
}

<head>
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <meta charset="utf-8">
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Blog style customer stylesheet https://startbootstrap.com/template-overviews/blog-home/-->
    <link href="~/css/blog-home.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin.min.css" rel="stylesheet">
    <link href="~/vendor/datatables/dataTables.bootstrap4.js" rel="stylesheet">
    <link href="~/css/half-slider.css" rel="stylesheet">
    <link href="css/grayscale.min.css" rel="stylesheet">
</head>

<h2>Edit Voting Table (Don't.)</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>VTestTbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Vid)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VBitcoin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VBitcoin)
                    @Html.ValidationMessageFor(model => model.VBitcoin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VEthereum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VEthereum)
                    @Html.ValidationMessageFor(model => model.VEthereum, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VBitcoinCash, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VBitcoinCash)
                    @Html.ValidationMessageFor(model => model.VBitcoinCash, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VLitecoin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VLitecoin)
                    @Html.ValidationMessageFor(model => model.VLitecoin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VRipple, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.VRipple)
                    @Html.ValidationMessageFor(model => model.VRipple, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FYPFinal/Views/Admin/Index.cshtml
@model IEnumerable<FYPFinal.Models.VoteFinal>

@{
    ViewBag.Title = "Index";

}



<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VBitcoin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VEthereum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VBitcoinCash)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VLitecoin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VRipple)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VBitcoin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VEthereum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VBitcoinCash)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VLitecoin)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VRipple)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Vid }) |
                @Html.ActionLink("Details", "Details", new { id = item.Vid }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Vid })
            </td>
        </tr>
    }

</table>

FYPFinal/Views/Admin/List.cshtml
@model IEnumerable<FYPFinal.Models.VoteFinal>

@{
    ViewBag.Title = "List";
    var grid = new WebGrid(source: Model, rowsPerPage: 20);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <meta charset="utf-8">
    <!-- Bootstrap core CSS-->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Blog style customer stylesheet https://startbootstrap.com/template-overviews/blog-home/-->
    <link href="~/css/blog-home.css" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="~/vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="~/css/sb-admin.min.css" rel="stylesheet">
    <link href="~/vendor/datatables/dataTables.bootstrap4.js" rel="stylesheet">
    <link href="~/css/half-slider.css" rel="stylesheet">
    <link href="css/grayscale.min.css" rel="stylesheet">
    <title>Voting List</title>
</head>

<body>
    <br />
    <br />
    <div>

        <h1> Display Voting Table contents & Delete Multiple Rows To Clear User Votes</h1>
        <br />
        @using (Html.BeginForm("Delete","Admin", FormMethod.Post))
        {
            @grid.GetHtml(
                tableStyle: "gridtable",
                columns: grid.Columns(

                    // add checkboxes for columns to delete
                    grid.Column(format: @<text><input type="checkbox" name="ids" value="@item.Vid" /></text>, header: "Select"),
                        grid.Column("Vid", "Vid"),
                                grid.Column("Date", "Date"),
                                grid.Column("Email", "Email"),
                                grid.Column("VBitcoin", "VBitcoin"),
                                grid.Column("VEthereum", "VEthereum"),
                                grid.Column("VBitcoinCash", "VBitcoinCash"),
                                grid.Column("VLitecoin", "VLitecoin"),
                                grid.Column("VRipple", "VRipple")
                    )
                )
            <input type="submit" value="Delete" />
        }
    </div>
</body>
</html>