FYPFinal/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FYPFinal.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }

        // GET: post1
        public ActionResult Post1()
        {
            return View();
        }

        // GET: post2
        public ActionResult Post2()
        {
            return View();
        }
    }
}

FYPFinal/Controllers/FundController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ChartLibrary;
using FYPFinal.Models;

namespace FYPFinal.Controllers
{
    public class FundController : Controller
    {
        // GET: Fund
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FundChart()
        {
            FundInstance objFundInstance = new FundInstance();
            FundDAL objFundRecord = new FundDAL();
            try
            {
                objFundInstance.FundInstanceList = objFundRecord.GetFundDetails();
                return View("~/Views/Fund/FundChart.cshtml", objFundInstance);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public JsonResult FundDashboardList(Int16? fundId)
        {
            FundInstance objFundInstance = new FundInstance();
            FundDAL objFundRecords = new FundDAL();
            if (object.Equals(fundId, null))
            {
                fundId = 1;
            }
            try
            {
                var response = objFundRecords.GetFundRecordByFundId(fundId);
                if (!object.Equals(response, null))
                {
                    objFundInstance.FundRecordsList = response.ToList();
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return Json(objFundInstance.FundRecordsList, JsonRequestBehavior.AllowGet);
        }

        //    private FundInstance db = new FundInstance();
        //    // GET: VTestTbls/Create
        //    public ActionResult Create()
        //    {
        //        return View();
        //    }

        //    // POST: VTestTbls/Create
        //    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //    [HttpPost]
        //    [ValidateAntiForgeryToken]
        //    public ActionResult Create([Bind(Include = "Vid,Date,VBitcoin,VEthereum,VBitcoinCash,VLitecoin,VRipple")] VoteFinal voteFinal)
        //    {
        //        if (ModelState.IsValid)
        //        {
        //            db.VoteFinals.Add(voteFinal);
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }

        //        return View(voteFinal);
        //    }
    }
}

FYPFinal/Controllers/VoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FYPFinal.Models;
using System.Web.Helpers;

namespace FYPFinal.Controllers
{
    public class VoteController : Controller
    {
        // Get: Index view for vote
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "Vid,Date,Email,VBitcoin,VEthereum,VBitcoinCash,VLitecoin,VRipple")]VoteFinal vote)
        {
            if (ModelState.IsValid)
            {
                using (FYPEntities db = new FYPEntities())
                {
                    db.VoteFinals.Add(vote);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View("Dash", "Dash");
        }

        public ActionResult VoteResults()
        {
            return View();
        }

        //usused for now
        public ActionResult CreateVotePie()
        {
            //Create bar chart
            var Vchart = new Chart(width: 300, height: 200)
            .AddSeries(chartType: "pie",
                            xValue: new[] { "10 ", "50", "30 ", "70" },
                            yValues: new[] { "50", "70", "90", "110" })
                            .GetBytes("png");
            return File(Vchart, "~/images");
        }
    }
}

FYPFinal/Views/Shared/_BlogLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<style type="text/css">
            body {
                background: navy !important;
            }
            /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
        </style>*@
</head>
<body class="bg-secondary">
    <!-- New Navbar, from: https://getbootstrap.com/docs/4.0/components/navbar/-->
    <nav class="navbar-fixed-top navbar-expand-lg navbar-dark bg-light">
        <!-- logo made with: https://logomakr.com/ -->
        <a href="#" class="navbar-left" onclick="@("window.location.href='" + @Url.Action("Dash","Dash") + "'");"><img src="~/images/BVLogo3.png" height="65px" width="450px"></a>
        @*<a class="navbar-brand" href="#">Navbar</a>*@
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="h1 navbar-btn nav-link" onclick="@("window.location.href='" + @Url.Action("FundChart","Fund") + "'");" href="#">Fund Info</a>
                <a class="h1 navbar-btn nav-link" onclick="@("window.location.href='" + @Url.Action("Index","Vote") + "'");" href="#">Voting</a>
                <a class="h1 navbar-btn nav-link" onclick="@("window.location.href='" + @Url.Action("Index","Blog") + "'");" href="#">Blog</a>
            </div>
        </div>
    </nav>


    @*<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="#">Features</a>
                    <a class="nav-item nav-link" href="#">Pricing</a>
                    <a class="nav-item nav-link disabled" href="#">Disabled</a>
                </div>
            </div>
        </nav>*@
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script type="text/javascript" src="@Url.Content("/vendor/jquery/jquery.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/popper/popper.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/bootstrap/js/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/jquery-easing/jquery.easing.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/chart.js/Chart.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/datatables/jquery.dataTables.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/datatables/dataTables.bootstrap4.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/sb-admin.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/sb-admin-datatables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/js/sb-admin-charts.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("//js/jquery-3.0.0.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("//js/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/grayscale.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/grayscale.min.js")"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FYPFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<style type="text/css">
        body {
            background: navy !important;
        }
        /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>*@
</head>
<body class="bg-light">
    <!-- New Navbar, from: https://getbootstrap.com/docs/4.0/components/navbar/-->
    <nav class="navbar-fixed-top navbar-expand-lg navbar-dark bg-dark">
        <!-- logo made with: https://logomakr.com/ -->
        <a href="#" class="navbar-left" onclick="@("window.location.href='" + @Url.Action("Dash","Dash") + "'");"><img src="~/images/BVLogo3.png" height="65px" width="450px"></a>
        @*<a class="navbar-brand" href="#">Navbar</a>*@
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="h1 navbar-btn nav-link" onclick="@("window.location.href='" + @Url.Action("FundChart","Fund") + "'");" href="#">Fund Info</a>
                <a class="h1 navbar-btn nav-link" onclick="@("window.location.href='" + @Url.Action("Index","Vote") + "'");" href="#">Voting</a>
                <a class="h1 navbar-btn nav-link" onclick="@("window.location.href='" + @Url.Action("Index","Blog") + "'");" href="#">Blog</a>
            </div>
        </div>
    </nav>


    @*<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="#">Features</a>
                <a class="nav-item nav-link" href="#">Pricing</a>
                <a class="nav-item nav-link disabled" href="#">Disabled</a>
            </div>
        </div>
    </nav>*@
    <div class="container-fluid">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script type="text/javascript" src="@Url.Content("/vendor/jquery/jquery.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/popper/popper.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/bootstrap/js/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/jquery-easing/jquery.easing.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/chart.js/Chart.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/datatables/jquery.dataTables.js")"></script>
    <script type="text/javascript" src="@Url.Content("/vendor/datatables/dataTables.bootstrap4.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/sb-admin.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/sb-admin-datatables.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/js/sb-admin-charts.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("//js/jquery-3.0.0.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("//js/bootstrap.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/grayscale.js")"></script>
    <script type="text/javascript" src="@Url.Content("/js/grayscale.min.js")"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>